# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ad99aee5c4abb333e7601e834e336af3aef9465b4ea44f396883db972205472efcb880a99176f4ea3e784b148ead49131b51a1962bc7ec8b1277f1e021258d8

test:
  secret_key_base: a2dd084f23fa9f1ca95176d3f0bd63e1f73be77c7791168fd3ebe32e00bee5671436c9e824f9f6b8a87d22b31cc7d1c2822a4ece131f82b3ed385c9163eb089c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
